// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// divMod
DataFrame divMod(NumericVector x, NumericVector d, bool shortForm);
RcppExport SEXP _MDMA_divMod(SEXP xSEXP, SEXP dSEXP, SEXP shortFormSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    Rcpp::traits::input_parameter< bool >::type shortForm(shortFormSEXP);
    rcpp_result_gen = Rcpp::wrap(divMod(x, d, shortForm));
    return rcpp_result_gen;
END_RCPP
}
// latinSquare
IntegerMatrix latinSquare(const R_len_t n);
RcppExport SEXP _MDMA_latinSquare(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const R_len_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(latinSquare(n));
    return rcpp_result_gen;
END_RCPP
}
// firstRow
IntegerVector firstRow(R_len_t n);
RcppExport SEXP _MDMA_firstRow(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< R_len_t >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(firstRow(n));
    return rcpp_result_gen;
END_RCPP
}
// mC_matrix
NumericMatrix mC_matrix(NumericMatrix x);
RcppExport SEXP _MDMA_mC_matrix(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mC_matrix(x));
    return rcpp_result_gen;
END_RCPP
}
// mC_vector
NumericVector mC_vector(NumericVector x);
RcppExport SEXP _MDMA_mC_vector(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(mC_vector(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MDMA_divMod", (DL_FUNC) &_MDMA_divMod, 3},
    {"_MDMA_latinSquare", (DL_FUNC) &_MDMA_latinSquare, 1},
    {"_MDMA_firstRow", (DL_FUNC) &_MDMA_firstRow, 1},
    {"_MDMA_mC_matrix", (DL_FUNC) &_MDMA_mC_matrix, 1},
    {"_MDMA_mC_vector", (DL_FUNC) &_MDMA_mC_vector, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_MDMA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
