# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title divmod
#' @description Return quotient and remainder from integer division of the input.
#'
#' `r lifecycle::badge("stable")`
#' @param x numeric value or vector
#' @param d numeric value or vector
#' @param shortForm boolean (defaults to \code{TRUE}), indicating whether the output should contain \code{x} and \code{d}
#'
#' @return \code{divMod} returns an object of class \code{divMod} (which is essentially a \code{data.frame}.)
#' Dependent upon the argument \code{shortForm}, the values of \code{x} and \code{d} are returned as well, which is especially useful when
#' recycling is used when \code{x} and \code{d} are of different length.
#'
#' @author Mathijs Deen
#' @export
#' @examples
#' divMod(x = 15, d = 4)
#' divMod(x = c(15,23,42,58), d = c(4,7), shortForm = FALSE) #recycling
#'
#' hh_mm_ss <- function(milliseconds) {
#'   seconds <- divMod(round(milliseconds/1000),60)
#'   minutes <- divMod(seconds$quotient, 60)
#'   hours   <- minutes$quotient
#'   seconds <- seconds$remainder
#'   minutes <- minutes$remainder
#'   sprintf("%02d:%02d:%02d", hours,minutes,seconds)
#' }
#'
#' hh_mm_ss(1000)
#' hh_mm_ss(68000)
#' hh_mm_ss(3680000)
#'
divMod <- function(x, d, shortForm = TRUE) {
    .Call(`_MDMA_divMod`, x, d, shortForm)
}

.meanCenter_Matrix <- function(x) {
    .Call(`_MDMA_mC_matrix`, x)
}

.meanCenter_Vector <- function(x) {
    .Call(`_MDMA_mC_vector`, x)
}

